### ISSUE TITLE
Multiple deployment strategies in the CC-Bridge

### ISSUE THREAD

**Issue by tedsuo** [cloudfoundry/diego-dev-notes#20]
The issue we are facing is the desire to support multiple Deployment strategies in CF (buildpack, docker, dot-net, app-container, etc...).  Ideally these deployment strategies work like "plugins", in that each CF deployment can consist of a different set of deployment strategies.

To accomplish this in the CC-Bridge, we have the concept of App-Lifecycle's.  This is currently sort-of pluggable, sort-of hardwired.  How should we re-architect the lifecycles to be fully pluggable?

Proposal is here: https://github.com/pivotal-cf-experimental/diego-dev-notes/blob/master/proposals/lifecycle-design.md

**Comment by ematpl** [comment]
Closing this out, as the CAPI team owns the CC-Bridge and the equivalent functionality in Cloud Controller itself.
